name: CI
on:
  push:
    branches: [ "main", "bootstrap/**", "feature/**" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11","3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test deps
        run: pip install -U pip pytest
      - name: Sanity tests
        run: pytest -q