name: Sync labels
on:
  workflow_dispatch:
  push:
    paths: [".github/labels.yml"]
permissions:
  issues: write
  metadata: read
  contents: read
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          skip-delete: true